#                                                            Developed by Acemix
#                                                        (Bilzox Studios @ (C) 2025)

name: IPSecurity
version: '${project.version}'
author: 'Acemix'

api-version: '1.20'
main: bilzox.acemix.studios.IPSecurity